name: PreRelease

on:
  workflow_run:
    workflows: ["MSBuild"]
    types:
      - completed  # Runs when MSBuild workflow is completed

permissions:
  contents: write  # Required to create a release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts  # Store all artifacts in this folder

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: PreRelease.${{ github.run_number }}  # Auto-incrementing version number
        name: OmegaWare Framework PreRelease ${{ github.run_number }}
        body: |
          ## What's Changed
          ${{ github.event.head_commit.message }}  # Automatically grabs the latest commit message as release notes
        draft: true  # Set to true if you want to review before publishing
        prerelease: true
        files: artifacts/Internal_*.zip  # Upload all build ZIPs
